title: My Jekyll Site
# Название вашего сайта. Это может отображаться в заголовке страницы или в других частях шаблона.

description: A simple description of my site
# Описание вашего сайта. Может использоваться для SEO и отображаться в мета-тегах.

baseurl: ""
# Базовый URL-адрес вашего сайта. Используется, если ваш сайт размещен не в корне домена, а в подкаталоге (например, /blog). Если сайт в корне, оставьте пустым.

url: "https://maksim22886.github.io/Massage/"
# Полный URL-адрес вашего сайта, включая протокол (http или https). Используется для генерации абсолютных URL-адресов на сайте.

# Настройки сборки
markdown: kramdown
# Указывает, какой процессор Markdown использовать. Kramdown - это стандартный процессор в Jekyll.

theme: minima
# Указывает тему, которую вы используете для вашего сайта. Minima — это одна из стандартных тем Jekyll.